#include $(src)/../../.config

EXTRA_CFLAGS =-DIRCTL_DEV_MAJOR=61 -DLIRC_SERIAL_TRANSMITTER -DLIRC_SERIAL_SOFTCARRIER -I$(src)

obj-$(CONFIG_LIRC_DEV)		+= lirc_dev/
obj-$(CONFIG_LIRC_ATIUSB)	+= lirc_atiusb/
obj-$(CONFIG_LIRC_BT829)	+= lirc_bt829/
obj-$(CONFIG_LIRC_I2C)		+= lirc_i2c/
obj-$(CONFIG_LIRC_IGORPLUGUSB)	+= lirc_igorplugusb/
obj-$(CONFIG_LIRC_IMON)		+= lirc_imon/
obj-$(CONFIG_LIRC_IT87)		+= lirc_it87/
obj-$(CONFIG_LIRC_ITE8709)	+= lirc_ite8709/
obj-$(CONFIG_LIRC_MCEUSB)	+= lirc_mceusb/
obj-$(CONFIG_LIRC_MCEUSB2)	+= lirc_mceusb2/
obj-$(CONFIG_LIRC_PARALLEL)	+= lirc_parallel/
obj-$(CONFIG_LIRC_SASEM)	+= lirc_sasem/
obj-$(CONFIG_LIRC_SERIAL)	+= lirc_serial/
obj-$(CONFIG_LIRC_SIR)		+= lirc_sir/
obj-$(CONFIG_LIRC_STREAMZAP)	+= lirc_streamzap/
obj-$(CONFIG_LIRC_TTUSBIR)	+= lirc_ttusbir/
obj-$(CONFIG_LIRC_GPIO)		+= lirc_gpio/
obj-$(CONFIG_LIRC_TTUSBIR)	+= lirc_ttusbir/
obj-$(CONFIG_LIRC_WPC8769L)	+= lirc_wpc8769l/
